name: Browser Tests
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dusk
          restore-keys: |
            dusk

      - name: Install dependencies
        run: |
          composer require "laravel/framework:9.*" "orchestra/testbench:7.*" "doctrine/dbal:^3.0" --no-interaction --no-update -vvv
          composer install --prefer-dist --no-interaction -vvv

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Build npm dependencies.
        run: |
          npm install

      - name: Build twill.
        run: ./vendor/bin/testbench twill:build --noInstall

      - name: Upgrade Chrome Driver
        run: ./vendor/bin/testbench dusk:chrome-driver

      - name: Run Dusk Tests
        run: |
          ./vendor/bin/phpunit --testsuite=Browser
